version: '3.7'

name: 'job-hub-compose'

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'jobhub'
    volumes:
      - job-hub-postgres:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U jobhub']
      interval: 10s
      timeout: 5s
    restart: unless-stopped

volumes:
  job-hub-postgres:
    name: job-hub-postgres
